# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\x08wsobjdet\"\x9d\x01\n\rDetectRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12\x0e\n\x06subnet\x18\x05 \x01(\t\x12\x11\n\tmin_score\x18\x06 \x01(\x02\x12\x10\n\x08min_area\x18\x07 \x01(\x02\x12\x12\n\nall_labels\x18\x08 \x01(\x08\"z\n\tDetection\x12\r\n\x05x_min\x18\x01 \x01(\x05\x12\r\n\x05y_min\x18\x02 \x01(\x05\x12\r\n\x05x_max\x18\x03 \x01(\x05\x12\r\n\x05y_max\x18\x04 \x01(\x05\x12\r\n\x05label\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x02\x12\x13\n\x0b\x63lass_index\x18\x07 \x01(\x05\"\xa0\x01\n\x0e\x44\x65tectResponse\x12\'\n\ndetections\x18\x01 \x03(\x0b\x32\x13.wsobjdet.Detection\x12\x19\n\x11inference_time_ms\x18\x02 \x01(\x02\x12\x15\n\rtotal_time_ms\x18\x03 \x01(\x02\x12\x13\n\x0bsubnet_used\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"\"\n\x10SetSubnetRequest\x12\x0e\n\x06subnet\x18\x01 \x01(\t\"J\n\x11SetSubnetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x15\n\ractive_subnet\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"w\n\x0eStatusResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x15\n\ractive_subnet\x18\x02 \x01(\t\x12\x19\n\x11\x61vailable_subnets\x18\x03 \x03(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x14\n\x0cweights_path\x18\x05 \x01(\t2\xd5\x01\n\x10\x44\x65tectionService\x12;\n\x06\x44\x65tect\x12\x17.wsobjdet.DetectRequest\x1a\x18.wsobjdet.DetectResponse\x12\x44\n\tSetSubnet\x12\x1a.wsobjdet.SetSubnetRequest\x1a\x1b.wsobjdet.SetSubnetResponse\x12>\n\tGetStatus\x12\x17.wsobjdet.StatusRequest\x1a\x18.wsobjdet.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTREQUEST']._serialized_start=30
  _globals['_DETECTREQUEST']._serialized_end=187
  _globals['_DETECTION']._serialized_start=189
  _globals['_DETECTION']._serialized_end=311
  _globals['_DETECTRESPONSE']._serialized_start=314
  _globals['_DETECTRESPONSE']._serialized_end=474
  _globals['_SETSUBNETREQUEST']._serialized_start=476
  _globals['_SETSUBNETREQUEST']._serialized_end=510
  _globals['_SETSUBNETRESPONSE']._serialized_start=512
  _globals['_SETSUBNETRESPONSE']._serialized_end=586
  _globals['_STATUSREQUEST']._serialized_start=588
  _globals['_STATUSREQUEST']._serialized_end=603
  _globals['_STATUSRESPONSE']._serialized_start=605
  _globals['_STATUSRESPONSE']._serialized_end=724
  _globals['_DETECTIONSERVICE']._serialized_start=727
  _globals['_DETECTIONSERVICE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
