# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import detection_pb2 as detection__pb2


class DetectionServiceStub(object):
    """Detection service for WS-Mask2Former model
    Enables IPC between Pylot container and model container
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/wsobjdet.DetectionService/Detect',
                request_serializer=detection__pb2.DetectRequest.SerializeToString,
                response_deserializer=detection__pb2.DetectResponse.FromString,
                )
        self.SetSubnet = channel.unary_unary(
                '/wsobjdet.DetectionService/SetSubnet',
                request_serializer=detection__pb2.SetSubnetRequest.SerializeToString,
                response_deserializer=detection__pb2.SetSubnetResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/wsobjdet.DetectionService/GetStatus',
                request_serializer=detection__pb2.StatusRequest.SerializeToString,
                response_deserializer=detection__pb2.StatusResponse.FromString,
                )


class DetectionServiceServicer(object):
    """Detection service for WS-Mask2Former model
    Enables IPC between Pylot container and model container
    """

    def Detect(self, request, context):
        """Run detection on a single image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSubnet(self, request, context):
        """Switch the active subnet configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current model status and configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=detection__pb2.DetectRequest.FromString,
                    response_serializer=detection__pb2.DetectResponse.SerializeToString,
            ),
            'SetSubnet': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSubnet,
                    request_deserializer=detection__pb2.SetSubnetRequest.FromString,
                    response_serializer=detection__pb2.SetSubnetResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=detection__pb2.StatusRequest.FromString,
                    response_serializer=detection__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wsobjdet.DetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectionService(object):
    """Detection service for WS-Mask2Former model
    Enables IPC between Pylot container and model container
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wsobjdet.DetectionService/Detect',
            detection__pb2.DetectRequest.SerializeToString,
            detection__pb2.DetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSubnet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wsobjdet.DetectionService/SetSubnet',
            detection__pb2.SetSubnetRequest.SerializeToString,
            detection__pb2.SetSubnetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wsobjdet.DetectionService/GetStatus',
            detection__pb2.StatusRequest.SerializeToString,
            detection__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
